### ISSUE TITLE
[1.14.4] Attempted invocation of a client-side only method during registration on servers

### ISSUE THREAD

**Issue by noobanidus** [c0d3break3r/Bloomful#15]
https://github.com/c0d3break3r/Bloomful/blob/master/src/main/java/com/pugz/bloomful/common/block/TrappedChestBlock.java#L22

```
java.lang.NoSuchMethodError: com.pugz.bloomful.common.block.TrappedChestBlock.provideItemBlock(Lnet/minecraft/item/Item$Properties;)V
	at com.pugz.bloomful.core.registry.BlockRegistry.registerItems(BlockRegistry.java:145)
	at net.minecraftforge.eventbus.ASMEventHandler_591_BlockRegistry_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
```

**Comment by Renadarain** [comment]
Hi :)

I too have this error.
