### ISSUE TITLE
crashes my game

### ISSUE THREAD

**Issue by keatonday** [c0d3break3r/Bloomful#31]
no matter what I try this mod will not work

**Comment by bageldotjpg** [comment]
Do you have a crash report?
What version of Minecraft are you on?
What version are you on of Bloomful?
Are you on Forge?
What version of Forge are you on?

**Comment by keatonday** [comment]
// I let you down. Sorry :(

Time: 2/23/20 5:34 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:526) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:190) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84)

-- Block model being tesselated --
Details:
	Block: Block{bloomful:pink_wisteria_vine}[half=lower]
	Block location: World: (-126,69,23), Chunk: (at 2,4,7 in -8,1; contains blocks -128,0,16 to -113,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
	Block: Block{bloomful:pink_wisteria_vine}[half=lower]
	Block location: World: (-126,69,23), Chunk: (at 2,4,7 in -8,1; contains blocks -128,0,16 to -113,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60)
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:526)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['JustCallMeKD'/166, l='MpServer', x=-41.49, y=75.25, z=-25.52]]
	Chunk stats: Client Chunk Cache: 1089, 729
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-32,75,-31), Chunk: (at 0,4,1 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 170 game time, 170 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 677158544 bytes (645 MB) / 4619501568 bytes (4405 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.1
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		curiousshulkerboxes-FORGE-1.14.4-1.0.0.2.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-1.0.0.2 DONE}
		chanceglobe-1.14.4-v1.3.jar Chance Globe {chanceglobe@v1.3 DONE}
		vilnames_1.14-1.4.jar Villager Names {vilnames@1.4 DONE}
		enchantable-1.1.0-1.14.4.jar Enchantable {enchantable@1.1.0 DONE}
		DoggyTalents-1.14.4-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		rsgauges-1.14.4-1.2.1.jar Gauges and Switches {rsgauges@1.2.1 DONE}
		XaerosWorldMap_1.5.5_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		citadel-1.0.3.jar Citadel {citadel@1.0.3 DONE}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 DONE}
		Uncrafted 1.14.4  (v.4.0.0 pre1).jar Uncrafted {uncrafted@4.0.0 DONE}
		guardvillagers-1.14.4-1.0.1.jar Guard Villagers {guardvillagers@1.0.1 DONE}
		ChanceCubes-1.14.4-4.0.0.298.jar Chance Cubes {chancecubes@1.14.4-4.0.0.298 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		Customized-Dungeon-Loot-1.14.x-(v.2.0.0).jar Customized Dungeon Loot {cdl@2.0.0 DONE}
		ProgressiveBosses-2.1.4.jar Progressive Bosses {progressivebosses@2.1.4 DONE}
		FpsReducer-mc1.14.4-1.14.1.jar FPS Reducer {fpsreducer@mc1.14.4-1.14.1 DONE}
		JustEnoughResources-1.14.4-0.10.1.74.jar Just Enough Resources {jeresources@0.10.1.74 DONE}
		Paraglider-1.14.4-1.1.0.2.jar Paraglider {paraglider@1.1.0.2 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		valhelsia_structures-1.14.4-0.0.2a.jar Valhelsia Structures {valhelsia_structures@1.14.4-0.0.2a DONE}
		seafaring-1.14.4-0.2.1.jar Seafaring {sea@0.2.1 DONE}
		grindst_1.14-1.2.jar Grindstone Sharper Tools {grindst@1.2 DONE}
		Uncharted_1.14.4_v05.jar Uncharted {uncharted@v05 DONE}
		simplylight-0.9.0.jar Simply Light {simplylight@0.9.0 DONE}
		simplefarming-1.14.4-1.2.8.jar Simple Farming {simplefarming@1.14.4-1.2.8 DONE}
		guardillagers-1.14.4-1.0.1.jar GuardIllagers {guardillagers@1.0.1 DONE}
		xercamod-1.14.4-1.4.jar Xerca Mod {xercamod@1.14.4-1.4 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		Botania r1.11-377.jar Botania {botania@r1.11-377 DONE}
		Patchouli-1.14.4-1.1-26.jar Patchouli {patchouli@1.14.4-1.1-25 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		extlights-1.8.jar Extended Lights {extlights@1.8 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		betteranimals-1.14.4-5.3.0.jar Cyber's Better Animal Models {betteranimals@5.3.0 DONE}
		tombstone-4.2.1-1.14.4.jar Corail Tombstone {tombstone@4.2.1 DONE}
		noRecipeBook_v1.4.1formc1.14.4.jar No Recipe Book {norecipebook@1.4.1 DONE}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 DONE}
		moreoverlays-1.16.1.jar More Overlays {moreoverlays@1.16.1 DONE}
		TropicalV1.0.0.jar Tropical {tropical@1.0.0 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		effortlessbuilding-1.14.4-2.16.jar Effortless Building {effortlessbuilding@1.14.4-2.16 DONE}
		UniversalClockHUD-1.0.jar Universal Clock HUD {universalclockhud@1.0.0 DONE}
		Cyclic-1.14.4-0.1.3.jar Cyclic {cyclic@1.14.4-0.1.3 DONE}
		SoundControl-1.14.4-0.1.0.0.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.14.4-0.1.0.0 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 DONE}
		EquipmentTooltips-1.14.4-1.3.2+10.jar Equipment Tooltips {equipmenttooltips@1.3.2+10 DONE}
		creeperfix-1.14.4-1.3.jar CreeperFix {creeperfix@1.3 DONE}
		SurvivalPlus-Lightsabers-1.14.4-0.1.3.jar SurvivalPlus Lightsabers {lightsaber@0.1.3 DONE}
		SurvivalPlus-1.14.4-0.1.2.jar SurvivalPlus {survivalplus@0.1.2 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		lumberjack-2.0.0.jar LumberJack {lumberjack@2.0.0 DONE}
		mining-helmet-1.14.4-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 DONE}
		vanillaexcavators-1.14.4-1.0.jar Vanilla Excavators {vanillaexcavators@1.14.4-1.0 DONE}
		bambooblocks-1.2.12.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		BirdsNestsAndTreasures-1.14.4-1.0.0.jar Birds Nests & Treasures {birdsneststres@1.0.0 DONE}
		caelus-FORGE-1.14.4-1.0.1.2.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.2 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		bloomful-1.2.4.jar Bloomful {bloomful@1.2.3 DONE}
		extraboats-1.2.4-1.14.4.jar Extra Boats {extraboats@1.2.4 DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		mgui-1.14.4-1.2.0.jar mgui {mgui@1.2.0 DONE}
		NaturesCompass-1.14.4-1.8.3.jar Nature's Compass {naturescompass@1.14.4-1.8.3 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		decorative_blocks_5.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		curioofundying-FORGE-1.14.4-2.0.1.jar Curio of Undying {curioofundying@FORGE-1.14.4-2.0.1 DONE}
		betteranimalsplus-1.14.4-8.2.1.jar Better Animals Plus {betteranimalsplus@8.2.1 DONE}
		FarmingForBlockheads_1.14.4-5.3.2.jar Farming for Blockheads {farmingforblockheads@5.3.2 DONE}
		The-Endergetic-Expansion-1.14.4-v1.1.2.jar The Endergetic Expansion {endergetic@1.1.2 DONE}
		nhacampfire_1.14-1.5.jar No Hostiles Around Campfire {nhacampfire@1.5 DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		rftoolsstorage-1.14-0.0.7-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.7-alpha DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		extdiamond-1.3.jar Extended Diamond {extdiamond@1.3 DONE}
		PackingTape-1.14.4-0.9.2.jar Packing Tape {packingtape@0.9.2 DONE}
		endercompass-1.1.jar Ender Compass {endercompass@1.1 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		forge-1.14.4-28.2.1-universal.jar Forge {forge@28.2.1 DONE}
		ruins-1.14.4.6.jar Ruins {ruins@1.14.4.6 DONE}
		ColossalChests-1.14.4-1.7.6.jar ColossalChests {colossalchests@1.7.6 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		forge-1.14.4-28.2.1-client.jar Minecraft {minecraft@1.14.4 DONE}
		cofh_core-1.14.4-0.3.1b.jar CoFH Core {cofh_core@0.3.1b DONE}
		ensorcellation-1.14.4-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		rftoolsutility-1.14-1.2.14-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.14-alpha DONE}
		Environs-1.14.4-0.1.0.0.jar §3Dynamic Surroundings: §eEnvirons {environs@1.14.4-0.1.0.0 DONE}
		EnchantmentDescriptions-1.14.4-1.3.9.jar EnchantmentDescriptions {enchdesc@1.3.9 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		ShadesOfNether-0.1.jar Shades of Nether {shadesofnether@1.0 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		UndergroundBiomes-1.14.4-1.0-53.jar Underground Biomes {undergroundbiomes@1.0-53 DONE}
		forbidden_arcanus-1.14.4-1.5.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5 DONE}
		rftoolsbuilder-1.14-1.2.12-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.12-alpha DONE}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 DONE}
		SpartanShields-1.14.4-2.0.0.jar Spartan Shields {spartanshields@2.0.0 DONE}
		Quark-r2.0-210.jar Quark {quark@r2.0-210 DONE}
		Charm-1.14.4-1.5.1.jar Charm {charm@1.14.4-1.5.1 DONE}
		Xaeros_Minimap_20.3.1.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.3.1.1 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		backpacked-1.4.0-1.14.4.jar Backpacked {backpacked@1.4.0 DONE}
		vanillahammers-1.14.4-1.0.jar Vanilla Hammers {vanillahammers@1.14.4-1.0 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		dde_1.14.4-1.0.jar Dragon Drops Elytra {dde@1.0 DONE}
		PickleTweaks-1.14.4-3.0.7.jar Pickle Tweaks {pickletweaks@3.0.7 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.14.4-1.0.19-b3.jar Engineer's Decor {engineersdecor@1.0.19-b3 DONE}
		nps_1.14-2.1.jar Nether Portal Spread {nps@2.1 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		illagers_plus-2.0.jar Illagers+ {illagers_plus@2.0(BETA) DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		CraftingCraft_1.14.4-7.1.7.jar CraftingCraft {craftingcraft@7.1.7 DONE}
		healingcf_1.14-1.7.jar Healing Campfire {healingcf@1.7 DONE}
		luckyores-1.14.4-1.3.1.jar Lucky Ores Mod {luckyores@1.3 DONE}
		BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
		pn_1.14-1.0.jar Pet Names {pn@1.0 DONE}
		xptome-1.14.4-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
	Launched Version: forge-28.2.1
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Lithos-Core v1.43 for 1.14.4.zip, file/Pablo's Zombies v2.zip, file/Pablo's Skeletons.zip, file/Pablo's Biome Vindicators and Evokers.zip, file/Pablo's Biome Pillagers and Witches.zip, mod:undergroundbiomesores, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by keatonday** [comment]
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:526) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:190) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84)

-- Block model being tesselated --
Details:
	Block: Block{bloomful:pink_wisteria_vine}[half=lower]
	Block location: World: (-126,69,23), Chunk: (at 2,4,7 in -8,1; contains blocks -128,0,16 to -113,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
	Block: Block{bloomful:pink_wisteria_vine}[half=lower]
	Block location: World: (-126,69,23), Chunk: (at 2,4,7 in -8,1; contains blocks -128,0,16 to -113,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60)
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:526)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['JustCallMeKD'/166, l='MpServer', x=-41.49, y=75.25, z=-25.52]]
	Chunk stats: Client Chunk Cache: 1089, 729
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-32,75,-31), Chunk: (at 0,4,1 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 170 game time, 170 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 677158544 bytes (645 MB) / 4619501568 bytes (4405 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.1
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0

**Comment by keatonday** [comment]
my forge version is 28.21 and bloomful is 1.2.4
Minecraft verion is 1.14.4
