### ISSUE TITLE
Server won't start 1.14.4

### ISSUE THREAD

**Issue by H4Mm3r** [c0d3break3r/Bloomful#43]
Forge 28.2.3
Bloomfull 1.2.4

[19:48:40] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2599/2056450725@13b0f40
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
        at net.minecraftforge.common.BiomeDictionary.listSupertypes(BiomeDictionary.java:360)
        at net.minecraftforge.common.BiomeDictionary.addTypes(BiomeDictionary.java:200)
        at com.pugz.bloomful.core.registry.BiomeRegistry.registerBiomesToDictionary(BiomeRegistry.java:28)
        at com.pugz.bloomful.core.Bloomful.setupCommon(Bloomful.java:38)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
        at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[19:48:40] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid bloomful
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212] {}
        at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_212] {}
        at net.minecraftforge.common.BiomeDictionary.listSupertypes(BiomeDictionary.java:360) ~[?:?] {re:classloading}
        at net.minecraftforge.common.BiomeDictionary.addTypes(BiomeDictionary.java:200) ~[?:?] {re:classloading}
        at com.pugz.bloomful.core.registry.BiomeRegistry.registerBiomesToDictionary(BiomeRegistry.java:28) ~[?:?] {re:classloading}
        at com.pugz.bloomful.core.Bloomful.setupCommon(Bloomful.java:38) ~[?:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:28.2] {re:classloading}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212] {}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_212] {}
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045) ~[?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404) ~[?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134) ~[?:?] {re:classloading}
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212] {}

[19:48:40] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[19:48:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Bloomful (bloomful) encountered an error during the common_setup event phase
§7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
[19:48:40] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/minecraft_server_beta/./crash-reports/crash-2020-04-12_19.48.40-server.txt
[19:48:40] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[19:48:40] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[19:48:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:979) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:521) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

**Comment by H4Mm3r** [comment]
Will it be fixed ? 1.14.4 abandonned ?

Thanks by advance

**Comment by bageldotjpg** [comment]
1.14 is abandoned and I can't reproduce this, I also never experienced this on my server in 1.14

**Comment by H4Mm3r** [comment]
Oh ok, thanks for having a look.
