### ISSUE TITLE
Crash with FastLeafDecay mod

### ISSUE THREAD

**Issue by greshdev** [c0d3break3r/Bloomful#55]
It seems that because the WisteriaLeavesBlock does not extends LeavesBlock, an issue is caused with the FastLeafDecay mod, which tries to cast the block to LeavesBlock, which fails and crashes the game.

```
Description: Exception in server tick loop

java.lang.ClassCastException: com.pugz.bloomful.common.block.WisteriaLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.olafkeijsers.fastleafdecay.FastLeafDecay$$Lambda$3350/1764390468.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2056/889260651.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```

**Comment by bageldotjpg** [comment]
FastLeafDecay should fix this on their end as it will apply to other mods. I thought they already had though
